### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zxc0254** [joeldenning/systemjs-webpack-interop#19]
ERROR in ./src/App.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
> <template>
|     <div>
|         <router-view></router-view>
 @ ./src/index.js 5:0-27 15:21-24
```

**If you do not need systemjs-webpack-interop, you can package it successfully and all loaders can be used, but with systemjs webpack interop, it will not work**

**Comment by zxc0254** [comment]
this is src/index.js

```
import Vue from 'vue'
import router from './router'
import store from './store'

import App from './App.vue'

import singleSpaVue from 'single-spa-vue'
import './set-public-path'

const vueLifecycles = singleSpaVue({
    Vue,
    appOptions: {
        render(h) {
            return h(App)
        },
        router,
        store,
        el: '#main'
    }
})
export const bootstrap = vueLifecycles.bootstrap
export const mount = vueLifecycles.mount
export const unmount = vueLifecycles.unmount
```

**Comment by joeldenning** [comment]
Hi @zxc0254, I do not see any way that systemjs-webpack-interop could impact vue loader. My guess is that your webpack configuration is incorrect somehow. Could you provide a demonstration of the issue?

**Comment by zxc0254** [comment]
Hi @joeldenning,This is my code address [](https://github.com/zxc0254/systemjs.git)

**Comment by joeldenning** [comment]
Thanks for providing the demonstration. The issue is that your code expects `checkWebpackConfig` to return the config, but it doesn't. From [this documentation](https://github.com/joeldenning/systemjs-webpack-interop#checkwebpackconfig):

> checkWebpackConfig(config)
> 
> config (required): A webpack config object to be verified. If the config object isn't following best practices for interop with systemjs, and error will be thrown.

I've created https://github.com/zxc0254/systemjs/pull/1, which shows the fix.

**Comment by zxc0254** [comment]
@joeldenning ok,thanks!
