### ISSUE TITLE
Interop plugin not respecting browserslist and not IE friendly (destructuring)

### ISSUE THREAD

**Issue by TheMcMurder** [joeldenning/systemjs-webpack-interop#22]
There are multiple uses of destructuring in files throughout the webpack plugin and it appears as though when using this in plugin mode the plugin includes the source code directly into the bundle. 

I couldn't figure out a clean way to force webpack to run the source code through babel before prepending it.

It may be possible to find the babel config -> find the supported browsers -> compile -> prepend automatically but I think it would be simplier to just remove the destructuring [here](https://github.com/joeldenning/systemjs-webpack-interop/blob/master/auto-public-path/1.js), [here](https://github.com/joeldenning/systemjs-webpack-interop/blob/master/auto-public-path/2.js), [here](https://github.com/joeldenning/systemjs-webpack-interop/blob/master/auto-public-path/3.js),  and [here](https://github.com/joeldenning/systemjs-webpack-interop/blob/master/auto-public-path/auto-public-path.js#L1).

I'm going to create an MR for this right away. If you can think of better way to do this let me know.

**Comment by TheMcMurder** [comment]
I also wonder if we're going about this the wrong way. It is possible to use the compiler given to us [here](https://github.com/joeldenning/systemjs-webpack-interop/blob/master/SystemJSPublicPathWebpackPlugin.js#L15) to compile the source code before appending it.

**Comment by TheMcMurder** [comment]
After thinking about this more I think the changes in #23 may be the simplest approach we can take, I see the following simple options:
1. Tell everyone to modify their webpack config to include this one node_module into their babel-loader to guarantee correct compatibility
2. Change the source to be compatible with the lowest common denominator or precompiled version for different targets

I think there are some really cool other options as well that would making sure the file is always parsed but I'm not sure if the difficulty in building it is worth the cost vs using a different syntax.

**Comment by joeldenning** [comment]
Resolved in #23

**Comment by TheMcMurder** [comment]
Thanks Joel! ❤️
