### ISSUE TITLE
Cannot read property 'meta' of undefined at autoPublicPath when loading MFE created with create-single-spa using Single-Spa-layout RootConfig build with Custom Webpack5 

### ISSUE THREAD

**Issue by ajasingh** [joeldenning/systemjs-webpack-interop#24]
Moving this issue from Single-Spa-Layout to this repository 
**The Root-Config is build using custom Webpack 5 and child mfe is created using Latest Version of Single-spa-cli and both have correct libraryTarget as 'system'**

We are getting below exception while loading a MFE created with create-single-spa CLI 
Uncaught TypeError: application '@test/test' died in status LOADING_SOURCE_CODE: Cannot read property 'meta' of undefined
    at autoPublicPath (auto-public-path.js:15)
    at Object../node_modules/systemjs-webpack-interop/auto-public-path/1.js (1.js:3)
    at __webpack_require__ (bootstrap:24)
    at startup:6
    at Object.execute (startup:7)
    at i (system-core.js:279)
    at e (system-core.js:275)
    at system-core.js:232

Root-Config-Webpack

const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin').CleanWebpackPlugin;

```
module.exports = {
	entry: path.resolve(process.cwd(), 'src/console-root-config.js'),
	target: ['web', 'es5'],
	output: {
		path: path.resolve(process.cwd(), 'dist'),
		libraryTarget: 'system',
		filename: 'bundle.js',
		uniqueName: 'console_rootconfig',
		publicPath: '',
	},
	module: {
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: [/node_modules/],
				use: ['babel-loader'],
			},
		],
	},
	externals: ['single-spa', 'react', 'react-dom', 'moment', 'styled-components', 'lodash', /^@console\/.*/],
	plugins: [new CleanWebpackPlugin()],
};
```

```
const applications = constructApplications({
			routes,
			loadApp({ name }) {
				if (name === '@console/middleware') {
					return Promise.resolve(middlewareApp);
				} else {
					return System.import(name);
				}
			},
		});
		const layoutEngine = constructLayoutEngine({ routes, applications, active: false });
```

```
<route path="test/test">
--
  | <application name="@test/test" loader="commonLoader" error="layoutError" props="getFeatureFlags,getUserProfile,getLocale,executionContext,getProductContext,getServerConfig,appConfig"></application>
  | </route>
```

**Comment by ajasingh** [comment]
HI @joeldenning  moving this issue from Single-Spa-Layout to this repo, both the root config and child mfe(Created using Single-Spa-Cli) are on webpack5 and are using libraryTarget: 'system'.

**Comment by ajasingh** [comment]
It is happening because of a polyfill which we are using to support some of the repositories which we have on webpack4 and to support some libraries like styled components we have kept this polyfill which is causing the mfes to break created with single spa cli

/* global System */

/** This is a workaround for webpack 4 and should be removed when upgraded to webpack 5.
 * This is required to make styled-components import work
 */

export const webpackPolyfill = () => {
	const originalInstantiate = System.constructor.prototype.instantiate;
	System.constructor.prototype.instantiate = function () {
		return originalInstantiate.apply(this, arguments).then(function (register) {
			const originalFn = register[1];
			register[1] = function (_export) {
				_export('__esModule', true);
				return originalFn.apply(this, arguments);
			};
			return register;
		});
	};
};

**Comment by joeldenning** [comment]
Hmm yeah that polyfill could interfere with things. If you can provide a demonstration repo, I can take a look. The way that it works is that when libraryTarget is set to `"system"` that it creates an output bundle with the following:

```
System.register([], function(__WEBPACK_EXPORT__, __system_context__) {
})
```

systemjs-webpack-interop's auto-public-path file uses `__system_context__.meta.url`. `__system_context__.meta` is equivalent to `import.meta` and is documented at https://github.com/systemjs/systemjs/blob/master/docs/system-register.md#importmeta.

If you'd like a workaround, you can use the approaches described in https://github.com/joeldenning/systemjs-webpack-interop#older-versions-of-webpack - they still work with webpack 5 even though the docs encourage using auto-public-path instead for webpack 5.

**Comment by ajasingh** [comment]
HI @joeldenning for now i patched the webpack 4 compatibility by specifically adding module name check in the webpack polyfill i hope this is fine 
```
export const webpackPolyfill = () => {
	const originalInstantiate = System.constructor.prototype.instantiate;
	System.constructor.prototype.instantiate = function (moduleName) {
		return originalInstantiate.apply(this, arguments).then(function (register) {
			if (moduleName === 'https://cdn.jsdelivr.net/npm/styled-components@5.1.1/dist/styled-components.min.js') {
				const originalFn = register[1];
				register[1] = function (_export) {
					_export('__esModule', true);
					return originalFn.apply(this, arguments);
				};
			}
			return register;
		});
	};
};
```

**Comment by joeldenning** [comment]
Glad to hear you got something working. This doesn't seem to be an issue with systemjs-webpack-interop, so I'm closing this issue
