### ISSUE TITLE
System.resolve still returns a promise with systemjs v6.8.3 

### ISSUE THREAD

**Issue by lorenzvanherwaarden** [joeldenning/systemjs-webpack-interop#26]
The public path isn't correctly set. I can see when debugging `setPublicPath` that System.resolve returns a promise and not a string. I checked #7 and we use systemjs v6.8.3, so it should return a string if I'm not mistaken. We also use webpack>4.30.0. We're doing the importmap with: _importmap resolve with <script type="systemjs-importmap" src="">_

**Comment by internettrans** [comment]
SystemJS 6.8.3's resolve function does not return a Promise. Here's proof: https://codesandbox.io/s/peaceful-knuth-r9ild?file=/index.html. See https://github.com/systemjs/systemjs/releases/tag/6.0.0 where this was part of the breaking changes between systemjs 5 and 6.

It's possible for SystemJS extras to override the `resolve` function to return a promise, so perhaps in your case you have an extra that is doing so?

One thing to note with systemjs@6 is that `System.resolve()` only works for bare specifiers once `System.prepareImport()` resolves. Before prepareImport finishes up, System.resolve will throw an error (still not return a promise, though) for bare specifiers.

I'm closing this as issue as it seems to be inaccurate. Feel free to reopen or comment further. To report a bug, please provide a demonstration.

**Comment by lorenzvanherwaarden** [comment]
@joeldenning Thanks for the help. After closer inspection with the insights you provided, the project handling the imports (which I don't work on) indeed does override System.resolve and returns a promise.
