### ISSUE TITLE
Error: systemjs-webpack-interop: There is no such module '@timo/navbar' in the SystemJS registry.

### ISSUE THREAD

**Issue by timoyan** [joeldenning/systemjs-webpack-interop#27]
Here is the single-spa application (ts + ssr)  to reproduce issue

https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr

You could pull it into local and run `yarn` to install all packages then run `yarn start`.

## Expect

I could put following setting in root config importmap file and application would work.
```
              "@timo/navbar": "http://localhost:8080/timo-navbar.js",
              "@timo/navbar/": "http://localhost:8080/",
```

## Actual

When I launch my root config project, always get error message 
```
Error: systemjs-webpack-interop: There is no such module '@timo/navbar' in the SystemJS registry. Did you misspell the name of your module?
```

I check the past issues and but unfortunately can't solve my issue, i suspect the issue only happened under combination `ts + ssr`. 

It works when I remove ts related in project, you could refer https://github.com/timoyan/single-spa-navbar-ssr/tree/master to get version without typescript.

**Comment by timoyan** [comment]
And I have another question about SSR

Actually I just want the root config have feature SSR but the rest application modules are able to load in client side only.

I learned from the example https://github.com/isomorphic-microfrontends but looks like all projects must have server side render setting.

Not sure is possible to implement my idea with current single-spa framework?

**Comment by timoyan** [comment]
I found the error is caused by window is undefined here. only happened when I am in (typescript + ssr) https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr

https://github.com/joeldenning/systemjs-webpack-interop/blob/4d7d952a7d900c3a1e4a878bf6ce7db616ee05a9/public-path.js#L30

**Comment by internettrans** [comment]
I'm only going to respond to the question relevant to systemjs-webpack-interop, please ask the server rendering question in a separate issue or on Slack.

Thanks for creating the demonstration repo. Unfortunately it doesn't work due to the yarn.lock referencing your company's private npm registry https://iherb.jfrog.io. I tried deleting the yarn.lock and trying again but then ran into compilation issues.

The error indicates that the bundle was loaded before the import maps were processed. System.resolve() throws an error for bare specifiers before the import maps are processed. The `System.prepareImport()` function is what processes the import maps and is called as part of `System.import()`. One possible explanation is that you're loading the code without calling `System.import()`. However, it's hard to diagnose further without seeing the code for the root config. The root config code is the most relevant, but is not in your demonstration repo, so even if the issue I mentioned above was solved I'd still not be able to diagnose the problem with your repo since it's missing the relevant code in the root config.

I'm closing this because there's no possible problem within systemjs-webpack-interop that could cause this. This is likely a problem with the code in your root config. If you can provide a working demo repo of both root config and navbar, I can diagnose further.

**Comment by timoyan** [comment]
Thanks replying.

Here is the root config demo repo, please follow the steps in readme to have local development environment
https://github.com/timoyan/single-spa-root-config-ssr

Also,
I confirmed the file `yarn.lock` and not include any private npm registry in branch `ts-ssr` of repo  `https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr`.

**Comment by timoyan** [comment]
> I'm only going to respond to the question relevant to systemjs-webpack-interop, please ask the server rendering question in a separate issue or on Slack.
> 
> Thanks for creating the demonstration repo. Unfortunately it doesn't work due to the yarn.lock referencing your company's private npm registry https://iherb.jfrog.io. I tried deleting the yarn.lock and trying again but then ran into compilation issues.
> 
> The error indicates that the bundle was loaded before the import maps were processed. System.resolve() throws an error for bare specifiers before the import maps are processed. The `System.prepareImport()` function is what processes the import maps and is called as part of `System.import()`. One possible explanation is that you're loading the code without calling `System.import()`. However, it's hard to diagnose further without seeing the code for the root config. The root config code is the most relevant, but is not in your demonstration repo, so even if the issue I mentioned above was solved I'd still not be able to diagnose the problem with your repo since it's missing the relevant code in the root config.
> 
> I'm closing this because there's no possible problem within systemjs-webpack-interop that could cause this. This is likely a problem with the code in your root config. If you can provide a working demo repo of both root config and navbar, I can diagnose further.

Thanks replying.

Here is the root config demo repo, please follow the steps in readme to have local development environment
https://github.com/timoyan/single-spa-root-config-ssr

Also,
I confirmed the file yarn.lock and not include any private npm registry in branch ts-ssr of repo https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr.

**Comment by internettrans** [comment]
> Here is the root config demo repo, please follow the steps in readme to have local development environment
https://github.com/timoyan/single-spa-root-config-ssr

You did not follow my instructions to create a separate github issue on the relevant repository for your server side rendering issue. Like I mentioned in my previous comment, please do that as I will not be responding to the SSR question in this thread. It is difficult for me to keep up with all of the issues and it becomes unmanageable if there are multiple separate threads within a single github issue.

> I confirmed the file yarn.lock and not include any private npm registry in branch ts-ssr of repo https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr.

This is false, see https://github.com/timoyan/single-spa-navbar-ssr/blob/626633b27e34b33e79ec5f5c6e0409fadbba6311/yarn.lock#L865. The https://iherb.jfrog.io/iherb domain is not a public npm registry. Please do not waste my time by saying that things are fixed when you did not fix them.

**Comment by timoyan** [comment]
> > Here is the root config demo repo, please follow the steps in readme to have local development environment
> > https://github.com/timoyan/single-spa-root-config-ssr
> 
> You did not follow my instructions to create a separate github issue on the relevant repository for your server side rendering issue. Like I mentioned in my previous comment, please do that as I will not be responding to the SSR question in this thread. It is difficult for me to keep up with all of the issues and it becomes unmanageable if there are multiple separate threads within a single github issue.
> 
> > I confirmed the file yarn.lock and not include any private npm registry in branch ts-ssr of repo https://github.com/timoyan/single-spa-navbar-ssr/tree/feature/ts-ssr.
> 
> This is false, see https://github.com/timoyan/single-spa-navbar-ssr/blob/626633b27e34b33e79ec5f5c6e0409fadbba6311/yarn.lock#L865. The https://iherb.jfrog.io/iherb domain is not a public npm registry. Please do not waste my time by saying that things are fixed when you did not fix them.

I really do apologize to not followed your instructions to submit github issue on the relevant repository.
Here is the issue I created in repository `single-spa`.

https://github.com/single-spa/single-spa/issues/882.

And I really do not waste your time on purpose. I actually fixed that issue in branch `feature/ts-ssr` but not in `master`. In order to make it convenient to you, I set the `feature/ts-ssr` as  default branch and delete `master`. Now you definitely not see private registry anymore. 

Really appreciate your time to check my question and feel sorry with my ignorant behavior.

**Comment by lmichailian** [comment]
@timoyan Did you solve this ? @joeldenning Why did you create SSR feature if dont have a minimun help o support.
