### ISSUE TITLE
System.resolve returns promise, not string, how it can work

### ISSUE THREAD

**Issue by DmitryBrus** [joeldenning/systemjs-webpack-interop#7]
I'm surprised how this tool can work properly,

since 
> moduleUrl = window.System.resolve(systemjsModuleName);

returns Promise and not a string 
https://github.com/systemjs/systemjs/issues/1909

Can somebody explain what I'm missing?

**Comment by joeldenning** [comment]
This is a duplicate of https://github.com/systemjs/systemjs/issues/1909#issuecomment-610924557. I responded there.

**Comment by DmitryBrus** [comment]
Thank you, I appreciate your help a lot, might be worth to mention required System.js version in documentation, 
since out of the box systemjs-webpack-interop throws not clear error.

**Comment by joeldenning** [comment]
The required SystemJS version is already listed in the readme at https://github.com/joeldenning/systemjs-webpack-interop#installation

> Note that systemjs-webpack-interop requires systemjs@>=6 and webpack@>=4.30.0

**Comment by DmitryBrus** [comment]
@joeldenning 
You are absolutely right, I just missed it! thanks a lot!
